### ISSUE TITLE
Document: how to install in VirtualBox

### ISSUE THREAD

**Issue by niconoe** [BelgianBiodiversityPlatform/BiodiversityBox#3]
Simple tutorial + FAQ for more advanced concepts?

**Comment by niconoe** [comment]
Topics: 

- how to enable copy-paste from guest to host
- network access
- file sharing
- screen size and resolution
- Keyboard layout

**Comment by stijnvanhoey** [comment]
The `copy-paste` feature is, from _long time ago_ experience a very important feature ;-)

**Comment by niconoe** [comment]
Documentation should be improved, but the basis is now ready.
