### ISSUE TITLE
Install software

### ISSUE THREAD

**Issue by niconoe** [BelgianBiodiversityPlatform/BiodiversityBox#5]
(List kept up-to-date for documentation purposes)

- [x] QGIS 
- QGIS plugins: 
    - [x] OpenLayers
    - [x] GBIF occurrences
- [x] R
- [x] RStudio
- R packages:
    - [x] tidyverse (= bundle of packages for data science we use all the time)
    - [x] rgbif (interface to GBIF)
    - [x] here (for better linking to files)
    - [x] janitor (for data cleaning)
    - [x] magrittr (for double pipe)
    - [x] digest (for creating hashes: useful for making IDs)
    - [x] readxl (for reading Excel files)
    - [x] install.packages(‘sdm’)  reproducible and extensible R platform for species distribution modelling
    - [x] install.packages('SSDM')  Stacked Species Distribution Models with R
    - [x] install.packages('Markdown') Markdown rendering for R
    - [x] devtools::install_github("inbo/inborutils") collection of useful R utilities and snippets
- [x] Tomcat + IPT (in test mode)
- [x] OpenRefine
- [x] Python 3 
- [x] pygbif, python-dwca-reader (in `myroot` conda environment)
- [x] Chromium or Firefox (with shortcuts to GBIF & co)
- [x] LibreOffice
- [x] CSVKit for CSV manipulation (in `myroot` conda environment)
- [x] Postgres/postgis
- [x] gdal  -> geographical transformations,...
- [x] miniconda, with installed packages:
    - [x] Numpy
    - [x] Pandas
    - [x] Seaborn
    - [x] Jupyter
- [x] inkscape -> vector image adaptations

**Comment by DimEvil** [comment]
Would not bother with MaxEnt. There are plenty of SDM packages in R and they are more often used than the original Maxent tool.  So I would inculde SDM in R

Maybe you could include Exploratory (Works in R, has a nice interface and a good strep in 'how to get used to R)

Would also include Jupyter noteboooks

**Comment by peterdesmet** [comment]
R packages (also inspired by our [checklist recipe](https://github.com/trias-project/checklist-recipe/blob/37f722f65cf5f369da68c57c9441e8f3bf225ce0/src/dwc_mapping.Rmd#L30-L38))

- [ ] tidyverse (= bundle of packages for data science we use all the time)
- [ ] rgbif (interface to GBIF)
- [ ] here (for better linking to files)
- [ ] janitor (for data cleaning)
- [ ] magrittr (for double pipe)
- [ ] digest (for creating hashes: useful for making IDs)
- [ ] readxl (for reading Excel files)

I'm not sure [Exploratory.io](https://exploratory.io/pricing) Desktop version exists for Linux

**Comment by DimEvil** [comment]
Ok, some SDM packages and other

- [ ] install.packages(‘sdm’)  reproducible and extensible R platform for species distribution modelling
- [ ] install.packages('SSDM')  Stacked Species Distribution Models with R
- [ ] install.packages('Markdown') Markdown rendering for R
- [ ] devtools::install_github("inbo/inborutils") collection of useful R utilities and snippets

**Comment by stijnvanhoey** [comment]
- [ ] gdal  -> geographical transformations,...
- [ ] miniconda -> see #9
- [ ] inkscape -> vector image adaptations

**Comment by mcoupremanne** [comment]
To be able to knit a rmd file towards a .doc or html, 'pandoc' should be installed (solved by **sudo pacman -S pandoc**)

**Comment by niconoe** [comment]
Closing, will open new issues for specific software as needed.
