### ISSUE TITLE
Install python packages

### ISSUE THREAD

**Issue by niconoe** [BelgianBiodiversityPlatform/BiodiversityBox#9]
Pandas, PyGBIF, python-dwca-reader, ... others? Consult INBO team?

**Comment by stijnvanhoey** [comment]
I would certainly include the typical-3 data science essential stack:
- [ ] numpy/scipy
- [ ] matplotlib
- [ ] pandas

With respect to plotting, I would add a few other packages:
- [ ] seaborn
- [ ] bokeh
- [ ] altair

and focus on mapping options as well:
- [ ] geopandas
- [ ] cartopy
- [ ] holoviews/geoviews

On the other hand, why not just provide miniconda in the box, so other packages can still be easily installed when necessury? miniconda is, in contradictrion to anaconda, lightweight.

**Comment by niconoe** [comment]
Miniconda is installed, and a base environment (with most packages already installed is created). Closing.
